services:
  casino-app:
    build: .
    command: ["./casino"]
    stdin_open: true
    tty: true
    container_name: casino-app
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: AKsoccer47
      MYSQL_DATABASE: casino

    ports:
      - "3307:3307"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: